### ISSUE TITLE
执行./gradlew build后编码错误  

### ISSUE THREAD

**Issue by yangzidemuou** [halo-sigs/halo-plugin-template#19]
执行./gradlew build后编码错误  
Task :compileJava
F:\code\halo-GPT\src\main\java\run\halo\starter\StarterPlugin.java:24: 错误: 编码 GBK 的不可映射字符 (0x81)
System.out.println("鎻掍欢鍚姩鎴愬姛锛?");
^
F:\code\halo-GPT\src\main\java\run\halo\starter\StarterPlugin.java:29: 错误: 编码 GBK 的不可映射字符 (0x81)
System.out.println("鎻掍欢鍋滄锛?");

在build.gradle中添加
tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
}

**Comment by JohnNiang** [comment]
请参考 <https://github.com/halo-dev/halo/pull/4844>。

Hi @yangzidemuou ，如果有兴趣的话，非常欢迎帮忙修复一下这个问题。
