### ISSUE TITLE
执行gradlew.bat haloServer报错Could not find io.github.guqing:halo:2.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by 907739769** [halo-sigs/halo-plugin-template#44]
D:\IdeaProjects\GitHub\plugin-starter>gradlew.bat haloServer
> Task :serverInstall FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':serverInstall'.
> Could not resolve all files for configuration ':compileOnly'.
   > Could not find io.github.guqing:halo:2.0.0-SNAPSHOT.
     Required by:
         project :

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m
2 actionable tasks: 2 executed

**Comment by guqing** [comment]
没有复现，请确保你的 plugin-starter 是最新的代码
![Image](https://github.com/user-attachments/assets/c566fe0a-a014-48ab-b1f2-e6596ddf17a2)

**Comment by 907739769** [comment]
> 没有复现，请确保你的 plugin-starter 是最新的代码 ![Image](https://github.com/user-attachments/assets/c566fe0a-a014-48ab-b1f2-e6596ddf17a2)

好吧 我那是两年前的代码😂
