### ISSUE TITLE
UI部分是否已经内置了tailwindcss？

### ISSUE THREAD

**Issue by wenjing-xin** [halo-sigs/halo-plugin-template#46]
我使用的是最新的开发模版，但是使用tailwindcss的一部分类名不生效，是缺少少了什么配置吗

**Comment by ruibaby** [comment]
默认没有集成任何样式库，需要自行集成。

另外，在 Halo 插件中更推荐使用 [UnoCSS](https://unocss.dev) 代替 TailwindCSS，因为 UnoCSS 支持 vue-scoped 模式，可以很好的解决样式污染的问题。

可以参考我在这里做出的改动：https://github.com/halo-sigs/plugin-migrate/pull/55

**Comment by wenjing-xin** [comment]
> 默认没有集成任何样式库，需要自行集成。
> 
> 另外，在 Halo 插件中更推荐使用 [UnoCSS](https://unocss.dev) 代替 TailwindCSS，因为 UnoCSS 支持 vue-scoped 模式，可以很好的解决样式污染的问题。
> 
> 可以参考我在这里做出的改动：[halo-sigs/plugin-migrate#55](https://github.com/halo-sigs/plugin-migrate/pull/55)

好的 谢谢解答！

**Comment by wenjing-xin** [comment]
很奇怪的是，我按照佬上述发的示例配置了后，在relaodPlugin的时候前端会报错：
```log
[ERROR] "unocss/vite" resolved to an ESM file. ESM file cannot be loaded by `require`. See https://vite.dev/guide/troubleshooting.html#this-package-is-esm-only for more details. [plugin externalize-deps]

    node_modules/.pnpm/esbuild@0.21.5/node_modules/esbuild/lib/main.js:1225:27:
      1225 │         let result = await callback({
           ╵                            ^
```
依赖版本和示例的一样是 0.61.5 ，后边在 https://blog.csdn.net/q1003675852/article/details/140014516  这个文章中按照第三点将unocss降级为 0.58.9后又好了，很奇怪

**Comment by ruibaby** [comment]
> 很奇怪的是，我按照佬上述发的示例配置了后，在relaodPlugin的时候前端会报错：
> ```log
> [ERROR] "unocss/vite" resolved to an ESM file. ESM file cannot be loaded by `require`. See https://vite.dev/guide/troubleshooting.html#this-package-is-esm-only for more details. [plugin externalize-deps]
> 
>     node_modules/.pnpm/esbuild@0.21.5/node_modules/esbuild/lib/main.js:1225:27:
>       1225 │         let result = await callback({
>            ╵                            ^
> ```
> 依赖版本和示例的一样是 0.61.5 ，后边在 https://blog.csdn.net/q1003675852/article/details/140014516  这个文章中按照第三点将unocss降级为 0.58.9后又好了，很奇怪

在 ui/package.json 添加 `type: "module"`

**Comment by wenjing-xin** [comment]
> module

好的 谢谢佬大，已解决😁
