### ISSUE TITLE
能否更新下基础模板的结构

### ISSUE THREAD

**Issue by liuyiwuqing** [halo-sigs/halo-plugin-template#48]
目前开发插件参考文档 [与其他插件交互时](https://docs.halo.run/developer-guide/plugin/interaction/dependency)
能否同步更新[plugin-starter](https://github.com/halo-dev/plugin-starter)，给一个规范的基础模板

**Comment by guqing** [comment]
plugin starter 并不适合将其改为分模块的，大部分插件是不需要分模块的，关于这一点后续会在文档补充并给出案例

可以参考 https://github.com/halo-dev/plugin-feed/pull/39 后续该仓库将被作为与其他插件交互的案例写在文档里
